### ISSUE TITLE
Using all things/stuffs for inference

### ISSUE THREAD

**Issue by ffahmed** [microsoft/X-Decoder#12]
I want to do inference for all possible things/stuffs XDecoder is trained on.
How do I construct the metadatacatalog (that would be used in inference), contain all these classes?

**Comment by MaureenZOU** [comment]
Please refer to here: https://github.com/microsoft/X-Decoder/blob/f3a10438fd40bf7e96dea31c36c1c66c3c791ecc/demo/demo_panoseg.py#L56

**Comment by ffahmed** [comment]
I meant to say if we don't know what things and stuffs we want from a picture, I want to tell it to give me all possible things and stuffs in panoptic seg. How do I do it?
