### ISSUE TITLE
Reopen Issue to Reclarify (unknown things/stuffs) : https://github.com/microsoft/X-Decoder/issues/12

### ISSUE THREAD

**Issue by ffahmed** [microsoft/X-Decoder#15]
About this issue (https://github.com/microsoft/X-Decoder/issues/12#issue-1584950185)

I meant to say if we don't know what things and stuffs we want from a picture, I want to tell it to give me all possible things and stuffs in panoptic seg. How do I do it?

**Comment by MaureenZOU** [comment]
Please go back to our paper, and other vl detection papers and understand the problem in a more detailed way. Thanks!

**Comment by jwyang** [comment]
@ffahmed what you asked is more like a dense or regional captioning task. but you can enumerate as many concepts as possible in the pool to mimic this behavior.
