### ISSUE TITLE
Small typo in the README

### ISSUE THREAD

**Issue by woctezuma** [microsoft/X-Decoder#16]
> * **[2022.02.07]** We combine <ins>X-Decoder</ins> (strong image understanding), <ins>GPT-3</ins> (strong language understanding) and <ins>Stable Diffusion</ins> (strong image generation) to make an [instructional image editing demo](https://huggingface.co/spaces/xdecoder/Instruct-X-Decoder), check it out!

The date should be `2023.02.07` instead of 2022, right?

**Comment by jwyang** [comment]
Thanks for reminding! @woctezuma
