### ISSUE TITLE
Wrong description in the HTML project page

### ISSUE THREAD

**Issue by woctezuma** [microsoft/X-Decoder#17]
When posting a link to [your project page](https://x-decoder-vl.github.io/) on Discord, the embedded text is wrong.

![Discord](https://i.imgur.com/gv6S60F.png)

This seems to be a copy-paste of the description of ["Nerfies: Deformable Neural Radiance Fields"](https://nerfies.github.io/).

You might want to edit the description in the HTML code of your project:

```html
  <meta name="description"
        content="Deformable Neural Radiance Fields creates free-viewpoint portraits (nerfies) from casually captured videos.">
  <meta name="keywords" content="Nerfies, D-NeRF, NeRF">
  <title>X-Decoder: Generalized Decoding for Pixel, Image and Language</title>
  ```

**Comment by MaureenZOU** [comment]
Thanks so much for your detailed reading!!! This has been fixed.
