### ISSUE TITLE
is the model can segment all types of classes?

### ISSUE THREAD

**Issue by Yaoxingtian** [microsoft/X-Decoder#19]
Hi,thanks for your great work!
 it sees x-decoder is zero-shot segment model, but when i test it by my data which including floor and bed   class , it can not work well, could you pls. explain it ? thanks!

**Comment by jwyang** [comment]
Hi, @Yaoxingtian,

thanks for rasing this question. Could you elaborate a bit more on how you use our x-decoder mode?

I just tried on image and it works well:

![image](https://user-images.githubusercontent.com/3894247/222340512-322a2007-b317-4b31-8141-1f9524f3a068.png)

**Comment by Yaoxingtian** [comment]
I tried all demo script in X-decoder,  and in segment demo, the stuff_classes just like: ['zebra','antelope','giraffe','ostrich','sky','water','grass','sand','tree'], there is no floor or sofa class, could you tell me how do you do that ?
what i did is:
python demo/demo_semseg.py evaluate --conf_files configs/xdecoder/svlp_focalt_lang.yaml  --overrides WEIGHT ./weights/xdecoder_focalt_best_openseg.pt

**Comment by Yaoxingtian** [comment]
![sem](https://user-images.githubusercontent.com/21310066/222653090-3e48a9ea-43d9-4c8a-b53a-584774da4c3d.png)

**Comment by jwyang** [comment]
You need to replace ['zebra','antelope','giraffe','ostrich','sky','water','grass','sand','tree'] with your own list of categories.

**Comment by Yaoxingtian** [comment]
> You need to replace ['zebra','antelope','giraffe','ostrich','sky','water','grass','sand','tree'] with your own list of categories.

you are right, now I know how to do that !
And ,can i use Open Vocabulary Segmentation:python eval.py to get this result too ?

**Comment by Yaoxingtian** [comment]
> You need to replace ['zebra','antelope','giraffe','ostrich','sky','water','grass','sand','tree'] with your own list of categories.

you are right, now I know how to do that !
How many class does xdecoder segment ?
And ,can i use Open Vocabulary Segmentation:python eval.py to get this result too ?

**Comment by jwyang** [comment]
You can segment an arbitrary number of categories, but please make sure you replace the categories with your own.
