### ISSUE TITLE
Traning code

### ISSUE THREAD

**Issue by jshilong** [microsoft/X-Decoder#2]
Thanks for the great work！
Will all the training code be released recently？

**Comment by MaureenZOU** [comment]
Thanks for your interest! The training code will not be released very soon (e.g. a month).

**Comment by yxchng** [comment]
@MaureenZOU will be training code still be released?

**Comment by MaureenZOU** [comment]
Yes, I will for sure release. We already have a public draft version support by openseed training pipeline.
