### ISSUE TITLE
Text Encoder src code

### ISSUE THREAD

**Issue by trqminh** [microsoft/X-Decoder#21]
Hi,
Thank you for your consideration.
Could you show me where I could find this part in the code?
<img width="180" alt="image" src="https://user-images.githubusercontent.com/30286786/222752738-2fb46bd8-daf1-49b9-aacb-988c77117817.png">

Thank you.

**Comment by MaureenZOU** [comment]
For grounding: https://github.com/microsoft/X-Decoder/blob/8f245b052a38d8d5410888d1bb52391050b4f726/xdecoder/body/decoder/xdecoder.py#L289
For Captioning: https://github.com/microsoft/X-Decoder/blob/8f245b052a38d8d5410888d1bb52391050b4f726/xdecoder/body/decoder/xdecoder.py#L231
