### ISSUE TITLE
Generic segmentation

### ISSUE THREAD

**Issue by trqminh** [microsoft/X-Decoder#24]
Hi @MaureenZOU ,
I have quick question about where is in the code for the arrow from Text Encoder to Semantic Output when inference.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/30286786/223139781-503be65f-5f12-45d2-8c87-368ec2677638.png">

**Comment by jwyang** [comment]
THe arrow from text encoder to semantic output simply means the dot product between the text embeddings and semantic outputs decoded from our X-Decoder. Please refer to this function: https://github.com/microsoft/X-Decoder/blob/8f245b052a38d8d5410888d1bb52391050b4f726/xdecoder/language/vlpencoder.py#L174
