### ISSUE TITLE
gpu cost duing training

### ISSUE THREAD

**Issue by JunMa11** [microsoft/X-Decoder#25]
Thanks for sharing the awesome work!

I have a minor question.

how many GPU hours does the model training process need on the COCO and ADE20K datasets?

**Comment by MaureenZOU** [comment]
That depends on whether you are doing the pretraining and finetuning, for finetuning:

COCO: 16 V100 gpus ~ 50h
ADE: 16 V100 gpus ~ 8h

**Comment by JunMa11** [comment]
Hi @MaureenZOU,

thanks for your quick reply very much.

How long does it take for pre-training?

**Comment by jwyang** [comment]
For a tiny model, it takes around 3-4 days with 32gpus to pre-train on COCO + VL data.
