### ISSUE TITLE
Missing file 'caption_class_similarity.pth'

### ISSUE THREAD

**Issue by huangrunhui** [microsoft/X-Decoder#27]
Hi, I found the coco dataset mapper missing this file 'caption_class_similarity.pth'. I'm wondering if you could release the script to generate this file.

https://github.com/microsoft/X-Decoder/blob/4cd2bb1e80e27d1aaefaaa3f62ab54b57029e0aa/datasets/dataset_mappers/coco_panoptic_new_baseline_dataset_mapper.py#L106

Besides, do you have any plans to release the training scripts?

**Comment by jwyang** [comment]
Hi, @huangrunhui, thanks for pointing out this, will fix the problem. Regarding the release of training code, we are decoupling it from our internal codebase, which may take a few weeks from now. thanks!

**Comment by tharkhay** [comment]
> Hi, I found the coco dataset mapper missing this file 'caption_class_similarity.pth'. I'm wondering if you could release the script to generate this file.
> 
> 
> 
> https://github.com/microsoft/X-Decoder/blob/4cd2bb1e80e27d1aaefaaa3f62ab54b57029e0aa/datasets/dataset_mappers/coco_panoptic_new_baseline_dataset_mapper.py#L106
> 
> 
> 
> Besides, do you have any plans to release the training scripts?

[](https://www.wps.com/d?from=a)

**Comment by MaureenZOU** [comment]
Please download the file at https://projects4jw.blob.core.windows.net/x-decoder/release/caption_class_similarity.pth
