### ISSUE TITLE
How to finetune custom datasets?

### ISSUE THREAD

**Issue by shiyongde** [microsoft/X-Decoder#28]
I have a custom datasets for instance segmentation , how can i finetune xdecoder for my dataset?

**Comment by MaureenZOU** [comment]
Thanks so much for your interests, I am currently working on training pipeline. Thanks!

**Comment by yuweihao** [comment]
Wonderful work! Looking forward to the training pipeline.

**Comment by tharkhay** [comment]
e

**Comment by MaureenZOU** [comment]
We have just released the training code and pipeline.
