### ISSUE TITLE
Hello together, first of all thank you for your work.

### ISSUE THREAD

**Issue by tharkhay** [microsoft/X-Decoder#29]
Hello together, first of all thank you for your work.
As part of my master thesis I am trying to bring the API to the Hololens, but unfortunately the app crashes as soon as I execute "open aicall gpt3". I am very grateful for any help!

_Originally posted by @dpxyz in https://github.com/KellanM/OpenAI-Api-Unreal/issues/11_

**Comment by jwyang** [comment]
Hi, @tharkhay , you may need to create your own OpenAI Key to make it work.
