### ISSUE TITLE
Question about caption finetune

### ISSUE THREAD

**Issue by zhouzhenghong-gt** [microsoft/X-Decoder#31]
Hello, thanks for your great work!

I would like to reproduce the results of caption finetuning. which dataset did you perform the caption finetuning?
And does the current code support finetune?

**Comment by tharkhay** [comment]
> Hello, thanks for your great work!
> 
> 
> 
> I would like to reproduce the results of caption finetuning. which dataset did you perform the caption finetuning?
> 
> And does the current code support finetune?
> 
> 
> 
> 
> 
> 
> 
>

**Comment by tharkhay** [comment]
> Hello, thanks for your great work!
> 
> 
> 
> I would like to reproduce the results of caption finetuning. which dataset did you perform the caption finetuning?
> 
> And does the current code support finetune?
> 
> 
> 
> 
> 
> 
> 
> 

[]()

**Comment by MaureenZOU** [comment]
This current code does not support finetuning, but the model and architecture provided supports. The dataset we are used for finetuning includes coco karparthy and flicker-30k karpathy split respectively.
