### ISSUE TITLE
**Why is this feature valuable to you? Does it solve a problem you're having?**

### ISSUE THREAD

**Issue by tharkhay** [microsoft/X-Decoder#37]
**Why is this feature valuable to you? Does it solve a problem you're having?**
A clear and concise description of why this feature is valuable. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. (if applicable)

**Additional context**

_Originally posted by @tharkhay in https://github.com/dropbox/dropbox-sdk-js/issues/1099_

**Comment by MaureenZOU** [comment]
This issue seems irrelevent.
