### ISSUE TITLE
Detach for text

### ISSUE THREAD

**Issue by vateye** [microsoft/X-Decoder#4]
Hi, I am quite confused about the loss computation. For computing the loss for learnable queries, I saw the text features are detached and thus will not be computing the gradient.  

https://github.com/microsoft/X-Decoder/blob/fca01f69542690e42d1a702a08944ae1af7bd4e2/xdecoder/body/decoder/xdecoder.py#L230

**Comment by MaureenZOU** [comment]
Hi, 
Text features are not detached for all the settings, they detach on output (per-layer) but attach on query_emb. This is an empirical design choice.

**Comment by vateye** [comment]
So, during the training on the tasks related to learnable queries (e.g., segmentation, grounding), the text features are always detached?

**Comment by MaureenZOU** [comment]
Nope, please go back to the code: https://github.com/microsoft/X-Decoder/blob/fca01f69542690e42d1a702a08944ae1af7bd4e2/xdecoder/body/decoder/xdecoder.py#L233

This is attached.
