### ISSUE TITLE
Referring captioning demo not using grounding mask

### ISSUE THREAD

**Issue by bhpfelix** [microsoft/X-Decoder#45]
Hi, thanks for the great work! Quick question about `demo/demo_refcap.py`: the grounding mask is zeroed out at [this line](https://github.com/microsoft/X-Decoder/blob/72f0701837a2ea0ede00aadc379e6d55cbfa6bab/demo/demo_refcap.py#L80), which seems counterintuitive if we want to pass it to the cross-attention layers. Should the line be removed for proper behavior?

**Comment by MaureenZOU** [comment]
Thanks so much for the question and dig the code too much! That line could be removed for proper behavior, I add it for debug purpose. Please go ahead to do this, I will update the code shortly.
