### ISSUE TITLE
Error about runing demo

### ISSUE THREAD

**Issue by wangxinyu6666** [microsoft/X-Decoder#46]
Your great work is awesome! When I try to run the demo_semseg.py script, and the error is as follows below, and how I can run successfully.
`
Traceback (most recent call last):
  File "D:\Projects\X-Decoder\demo\demo_instseg.py", line 97, in <module>
    main()
  File "D:\Projects\X-Decoder\demo\demo_instseg.py", line 40, in main
    opt, cmdline_args = load_opt_command(args)
  File "D:\Projects\X-Decoder\utils\arguments.py", line 69, in load_opt_command
    assert len(cmdline_args.overrides) % 2 == 0, "overrides arguments is not paired, required: key value"
AssertionError: overrides arguments is not paired, required: key value
`
How I can input the correct "overrides arguments"? thank you.

**Comment by MaureenZOU** [comment]
I think you forget to input the value of one argument

**Comment by wangxinyu6666** [comment]
> I think you forget to input the value of one argument↳

Sorry, I didn't forget it. this is my input:
`D:/Projects/X-Decoder/demo/demo_instseg.py evaluate --conf_files D:\Projects\X-Decoder\configs\xdecoder\svlp_focalt_lang.yaml --overrides D:\Projects\X-Decoder\xdecoder_focalt_best_openseg.pt`

I don't know where did I wrong? Can you give me a tip?

**Comment by MaureenZOU** [comment]
D:/Projects/X-Decoder/demo/demo_instseg.py evaluate --conf_files D:\Projects\X-Decoder\configs\xdecoder\svlp_focalt_lang.yaml D:\Projects\X-Decoder\xdecoder_focalt_best_openseg.pt

**Comment by MaureenZOU** [comment]
BTW, I never test the code on windows machine. So, not sure whether all the dependency works well. Need to be fixed by user, if you are able to run on windows feel free to have a push request on how you make windows work.
