### ISSUE TITLE
Clarification on Referring Segmentation

### ISSUE THREAD

**Issue by yxchng** [microsoft/X-Decoder#57]
Based on the code:

https://github.com/microsoft/X-Decoder/blob/584123df0792cfbee7500d7a5ea8c3878d146122/datasets/dataset_mappers/refcoco_dataset_mapper.py#L158

https://github.com/microsoft/X-Decoder/blob/584123df0792cfbee7500d7a5ea8c3878d146122/xdecoder/architectures/xdecoder_model.py#L419-L424

Is it true that referring segmentation in X-Decoder is done by segmentation -> classification (matching mask with highest similarity)?

**Comment by MaureenZOU** [comment]
Yes, but we are not directly matching the mask embedding, we compute hungarian matching between pred mask and gt mask, pred text embedding and gt text embedding. During evaluation we use text embedding matching score only.
