### ISSUE TITLE
Extension to Video Datasets

### ISSUE THREAD

**Issue by kanji95** [microsoft/X-Decoder#6]
How do we extend x-decoder to video datasets? In the appendix, it is mentioned that the model generalizes to generic segmentation and referring segmentation on videos.

**Comment by MaureenZOU** [comment]
Thanks for your question, the evaluated video dataset is simply evaluated frame by frame. For referring segmentation, the referring phrase is a natural tracking id, for segmentation we didn't apply any tracking.
