### ISSUE TITLE
coco_caption.zip download link is invalid

### ISSUE THREAD

**Issue by junwuzhang19** [microsoft/X-Decoder#61]
when I run install_cococapeval.sh, I cannot download coco_caption.zip and it returned PublicAccessNotPermitted Error. I wonder how to solve this? Thanks for your work!

**Comment by jwyang** [comment]
Please use this link to download: https://drive.google.com/file/d/1FHEQNkW7zHvSd-R8CQPC1gIuigC9w8Ff/view?usp=sharing
