### ISSUE TITLE
Segmentation in the Wild dataset

### ISSUE THREAD

**Issue by janzd** [microsoft/X-Decoder#65]
I cannot download the dataset for Segmentation in the Wild benchmark.
This link ( https://projects4jw.blob.core.windows.net/x-decoder/release/seginw.zip ) provided in the readme doesn't work and gives me a PublicAccessNotPermitted error. How can I download the dataset?

**Comment by jwyang** [comment]
Please find the dataset from this link: https://drive.google.com/file/d/1Q8yCRVxB3f3eBDTId33l79eYs4-gy1xu/view?usp=sharing

**Comment by janzd** [comment]
Thank you!
