### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'caption_class_similarity.pth'

### ISSUE THREAD

**Issue by fangdaoyou** [microsoft/X-Decoder#69]
Thank you for your great work.
when I try to run the train script, I met a error, can you give me some help?
I met the error when run the commend:

```sh
CUDA_VISIBLE_DEVICES=0 python entry.py train \
            --conf_files configs/xdecoder/segvlp_focalt_lang.yaml \
            --overrides \
            COCO.INPUT.IMAGE_SIZE 1024 \
            MODEL.DECODER.CAPTIONING.ENABLED True \
            MODEL.DECODER.RETRIEVAL.ENABLED True \
            MODEL.DECODER.GROUNDING.ENABLED True \
            MODEL.DECODER.CAPTIONING_WEIGHT 8 \
            MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
            MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
            MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
            MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
            COCO.TEST.BATCH_SIZE_TOTAL 1 \
            COCO.TRAIN.BATCH_SIZE_TOTAL 1 \
            COCO.TRAIN.BATCH_SIZE_PER_GPU 1 \
            VLP.TEST.BATCH_SIZE_TOTAL 32 \
            VLP.TRAIN.BATCH_SIZE_TOTAL 32 \
            VLP.TRAIN.BATCH_SIZE_PER_GPU 32 \
            MODEL.DECODER.HIDDEN_DIM 512 \
            MODEL.ENCODER.CONVS_DIM 512 \
            MODEL.ENCODER.MASK_DIM 512 \
            FP16 True \
```
 and met:
FileNotFoundError: [Errno 2] No such file or directory: 'caption_class_similarity.pth',
where to download the pth file?

**Comment by fangdaoyou** [comment]
sorry, I met the error when run the commend:
CUDA_VISIBLE_DEVICES=0 python entry.py train \
            --conf_files configs/xdecoder/segvlp_focalt_lang.yaml \
            --overrides \
            COCO.INPUT.IMAGE_SIZE 1024 \
            MODEL.DECODER.CAPTIONING.ENABLED True \
            MODEL.DECODER.RETRIEVAL.ENABLED True \
            MODEL.DECODER.GROUNDING.ENABLED True \
            MODEL.DECODER.CAPTIONING_WEIGHT 8 \
            MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
            MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
            MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
            MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
            COCO.TEST.BATCH_SIZE_TOTAL 1 \
            COCO.TRAIN.BATCH_SIZE_TOTAL 1 \
            COCO.TRAIN.BATCH_SIZE_PER_GPU 1 \
            VLP.TEST.BATCH_SIZE_TOTAL 32 \
            VLP.TRAIN.BATCH_SIZE_TOTAL 32 \
            VLP.TRAIN.BATCH_SIZE_PER_GPU 32 \
            MODEL.DECODER.HIDDEN_DIM 512 \
            MODEL.ENCODER.CONVS_DIM 512 \
            MODEL.ENCODER.MASK_DIM 512 \
            FP16 True \

> Thank you for your great work.
> when I try to run the train script, I met a error, can you give me some help?
> I follow the INSTALL.md, and met:
> FileNotFoundError: [Errno 2] No such file or directory: 'caption_class_similarity.pth'

**Comment by jwyang** [comment]
Hi, thanks for pointing out this problem! Please find the file here: https://github.com/microsoft/X-Decoder/releases/download/coco/caption_class_similarity.pth

**Comment by fangdaoyou** [comment]
> Hi, thanks for pointing out this problem! Please find the file here: https://github.com/microsoft/X-Decoder/releases/download/coco/caption_class_similarity.pth

thank you for early reply, but I found another file missed, LOL.
FileNotFoundError: [Errno 2] No such file or directory: '/yize/datasets/coco/annotations/panoptic_train2017_filtrefgumdval_filtvlp.json'

**Comment by MaureenZOU** [comment]
https://huggingface.co/xdecoder/X-Decoder/blob/main/captions_train2017_filtrefgumdval_filtvlp.json
https://huggingface.co/xdecoder/X-Decoder/blob/main/grounding_train2017_filtrefgumdval_filtvlp.json
