### ISSUE TITLE
sh install_cococapeval.sh : [ERROR 409: Public access is not permitted on this storage account..]

### ISSUE THREAD

**Issue by kokist** [microsoft/X-Decoder#70]
Thank you for your great work.

I ran install_cococapeval.sh and got the following error.
Error Description:
--2023-07-21 18:39:40--
Resolving projects4jw.blob.core.windows.net (projects4jw.blob.core.windows.net)... 20.60.153.33
Connecting to projects4jw.blob.core.windows.net (projects4jw.blob.core.windows.net)|20.60.153.33|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-07-21 18:39:40 ERROR 409: Public access is not permitted on this storage account..

Probably because this URL [https://projects4jw.blob.core.windows.net/x-decoder/release/coco_caption.zip] is not publicly available.
Can you give us public access to your resources?

**Comment by jwyang** [comment]
Thanks for pointing out! I had just updated the link to: https://huggingface.co/xdecoder/X-Decoder/resolve/main/coco_caption.zip. Please give it try.
