### ISSUE TITLE
About X-Decoder

### ISSUE THREAD

**Issue by 1020154KazumaSato** [microsoft/X-Decoder#73]
Thank you for your great work.

I’m trying to run X-Decoder in a local environment.

For Train and Evaluation, what kind of PC specs do you expect when running on a Single GPU?

Also, for DATASET.md, do I need to download the entire dataset?

Finally, regarding the demo, when do you plan to release it?

I look forward to hearing from you.

**Comment by MaureenZOU** [comment]
1. training is not able to run on a single gpu. it is run on 32 V100 gpus.
2. you can run inference code on a single gpu.
3. for training/evaluation, yes you need to download the whole dataset.
4. we have already release the demo, please refer to hugging face: https://huggingface.co/spaces/xdecoder/Demo/tree/main
