### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by jdj2261** [microsoft/X-Decoder#74]
Hello, 

Thank you so much for updating the file related to training.

I would like to request one correction regarding the Training Dataset.

When three json files were downloaded by wget, 

`captions_train2017_filtrefgumdval_filtvlp.json`
`grounding_train2017_filtrefgumdval_filtvlp.json`
`panoptic_train2017_filtrefgumdval_filtvlp.json`

I found that the file format is not json but html.

So, I changed it to the address listed on the hugging face.

```
wget -P ../xdecoder_data https://huggingface.co/xdecoder/X-Decoder/resolve/main/captions_train2017_filtrefgumdval_filtvlp.json
wget -P ../xdecoder_data https://huggingface.co/xdecoder/X-Decoder/resolve/main/grounding_train2017_filtrefgumdval_filtvlp.json
wget -P ../xdecoder_data https://huggingface.co/xdecoder/X-Decoder/resolve/main/panoptic_train2017_filtrefgumdval_filtvlp.json
```

Please confirm and thank you again.

**Comment by MaureenZOU** [comment]
Yeap, that is fully correct! So do you mean the current command only get html file? Thanks!
