### ISSUE TITLE
install_cococapeval.sh in seginw branch does not work

### ISSUE THREAD

**Issue by janzd** [microsoft/X-Decoder#77]
I tried downloading the zip file directly by using
`wget https://projects4jw.blob.core.windows.net/x-decoder/release/coco_caption.zip`
but it does not work. Can you re-upload the zip file?

**Comment by karimumar98** [comment]
Hi, In the main branch, the URL used is: https://huggingface.co/xdecoder/X-Decoder/resolve/main/coco_caption.zip, seems to work for me

**Comment by janzd** [comment]
Yeah, that works! Thanks!

**Comment by MaureenZOU** [comment]
Yes, we have uploaded the checkpoint to https://huggingface.co/xdecoder/X-Decoder/resolve/main/coco_caption.zip
