### ISSUE TITLE
'refcocog_umd_val.json' file not found

### ISSUE THREAD

**Issue by VH12138** [microsoft/X-Decoder#80]
Hi, when I try to evaluate X-Decoder using suggested refcocog dataset, I met this error saying 'refcocog_umd_VAL.json' file not found. After checking the script, 'refcoco2json.py' only help to produce the file 'refcocog_umd_TRAIN.json'. However, if I simply modified the refdcoco2json file dir from train2017 to val2017, the script does not work. Thus, I want to ask how can I create the file 'refcocog_umd_val.json' as required?

**Comment by MaureenZOU** [comment]
Please refer to https://huggingface.co/xdecoder/X-Decoder/blob/main/refcocog_umd_val.json
