### ISSUE TITLE
Question for coco2014 and coco2017

### ISSUE THREAD

**Issue by Espere-1119-Song** [microsoft/X-Decoder#82]
In this [link](https://github.com/dandelin/ViLT/blob/master/DATA.md)， [2014 train images](http://images.cocodataset.org/zips/train2014.zip), [2014 val images](http://images.cocodataset.org/zips/val2014.zip) is needed. However, in [4M Image Text Pairs](https://github.com/microsoft/X-Decoder/blob/main/asset/DATASET.md), coco2017 is needed.Which is exactly needed?

**Comment by MaureenZOU** [comment]
We are using 2014 train for 4m image text pairs, and exclude the coco2014 validation images for segmentation training.
