### ISSUE TITLE
SUN-37 dataset

### ISSUE THREAD

**Issue by Wang-pengfei** [microsoft/X-Decoder#83]
How to process the sun rgbd dataset, can you update this part in the readme?

**Comment by MaureenZOU** [comment]
We are using this split: https://github.com/chrischoy/SUN_RGBD/blob/master/test37.txt

**Comment by Wang-pengfei** [comment]
Hi, I found that there are 0-37 in the label, that is, there are 38 gt labels in total. This is inconsistent with the 37 categories. Is there any problem in the data?

**Comment by MaureenZOU** [comment]
Do you mean X-Decoder has 38 gt labels or their code has 38 gt labels? Thanks!

**Comment by Wang-pengfei** [comment]
There are 0-37 and 255 in the mask provided in this link：https://github.com/chrischoy/SUN_RGBD/blob/master/test37.txt
