### ISSUE TITLE
Possiblity of sharing fine-tuned model for image captioining

### ISSUE THREAD

**Issue by ByungKwanLee** [microsoft/X-Decoder#94]
Cau you share fine-tuned model for image captioining??

**Comment by MaureenZOU** [comment]
We are only able to share the Focal-T model if you are interested : )

**Comment by ByungKwanLee** [comment]
I love it! Thank you for the quick reply! How can I get it?

**Comment by MaureenZOU** [comment]
Feel free to download at: https://huggingface.co/xdecoder/X-Decoder/blob/main/xdecoder_focalt_captioning.pt
